In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv(f'./data/train.csv')
test = pd.read_csv(f'./data/test.csv')
trn_ob = pd.read_csv(f'./data/train_ob_charges.csv')  # open bab
tst_ob = pd.read_csv(f'./data/test_ob_charges.csv')   # open bab
trn_geom = pd.read_csv(f'./data/train_geom.csv')
tst_geom = pd.read_csv(f'./data/test_geom.csv')
dipole_moments = pd.read_csv(f'./data/dipole_moments.csv')
magnetic_shielding_tensors = pd.read_csv(f'./data/magnetic_shielding_tensors.csv')
mulliken_charges = pd.read_csv(f'./data/mulliken_charges.csv')
potential_energy = pd.read_csv(f'./data/potential_energy.csv')
scal_coup_contrib = pd.read_csv(f'./data/scalar_coupling_contributions.csv')
# sub = pd.read_csv(f'sample_submission.csv')
structures = pd.read_csv(f'./data/structures.csv')

In [4]:
train.head(20)

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant
0,0,dsgdb9nsd_000001,1,0,1JHC,84.80760
1,1,dsgdb9nsd_000001,1,2,2JHH,-11.25700
2,2,dsgdb9nsd_000001,1,3,2JHH,-11.25480
3,3,dsgdb9nsd_000001,1,4,2JHH,-11.25430
4,4,dsgdb9nsd_000001,2,0,1JHC,84.80740
5,5,dsgdb9nsd_000001,2,3,2JHH,-11.25410
6,6,dsgdb9nsd_000001,2,4,2JHH,-11.25480
7,7,dsgdb9nsd_000001,3,0,1JHC,84.80930
8,8,dsgdb9nsd_000001,3,4,2JHH,-11.25430
9,9,dsgdb9nsd_000001,4,0,1JHC,84.80950
10,10,dsgdb9nsd_000002,1,0,1JHN,32.68890
11,11,dsgdb9nsd_000002,1,2,2JHH,-11.18660
12,12,dsgdb9nsd_000002,1,3,2JHH,-11.17570
13,13,dsgdb9nsd_000002,2,0,1JHN,32.68910
14,14,dsgdb9nsd_000002,2,3,2JHH,-11.17580
15,15,dsgdb9nsd_000002,3,0,1JHN,32.69050
16,16,dsgdb9nsd_000003,1,2,2JHH,-9.94641
17,17,dsgdb9nsd_000005,2,0,1JHC,171.22000
18,18,dsgdb9nsd_000005,2,1,2JHN,5.18246
19,19,dsgdb9nsd_000007,2,0,1JHC,83.54290

In [5]:
test.head(10)

        id     molecule_name  atom_index_0  atom_index_1  type
0  4658147  dsgdb9nsd_000004             2             0  2JHC
1  4658148  dsgdb9nsd_000004             2             1  1JHC
2  4658149  dsgdb9nsd_000004             2             3  3JHH
3  4658150  dsgdb9nsd_000004             3             0  1JHC
4  4658151  dsgdb9nsd_000004             3             1  2JHC
5  4658152  dsgdb9nsd_000015             3             0  1JHC
6  4658153  dsgdb9nsd_000015             3             2  3JHC
7  4658154  dsgdb9nsd_000015             3             4  2JHH
8  4658155  dsgdb9nsd_000015             3             5  2JHH
9  4658156  dsgdb9nsd_000015             4             0  1JHC

In [8]:
trn_ob.head(20)

,Unnamed: 0,molecule_name,atom_index,eem,mmff94,gasteiger,qeq,qtpie,eem2015ha,eem2015hm,eem2015hn,eem2015ba,eem2015bm,eem2015bn,error
0,0,dsgdb9nsd_000001,0,-0.644531,0.0000,-0.077596,3.251140,-3.093807,0.014606,-0.813021,-0.784944,-0.067349,-0.806339,-0.851258,0
1,1,dsgdb9nsd_000001,1,0.161131,0.0000,0.019399,-0.812772,0.773439,-0.003651,0.203254,0.196234,0.016837,0.201583,0.212813,0
2,2,dsgdb9nsd_000001,2,0.161132,0.0000,0.019399,-0.812776,0.773442,-0.003651,0.203254,0.196235,0.016837,0.201584,0.212813,0
3,3,dsgdb9nsd_000001,3,0.161134,0.0000,0.019399,-0.812797,0.773463,-0.003651,0.203256,0.196237,0.016837,0.201586,0.212816,0
4,4,dsgdb9nsd_000001,4,0.161134,0.0000,0.019399,-0.812795,0.773462,-0.003651,0.203256,0.196237,0.016837,0.201586,0.212816,0
5,5,dsgdb9nsd_000002,0,-0.931923,-1.0800,-0.451940,2.150686,-1.928544,-1.088976,-1.089901,-0.888107,-0.965422,-0.974099,-0.856768,0
6,6,dsgdb9nsd_000002,1,0.310640,0.3600,0.150647,-0.716872,0.642826,0.362990,0.363299,0.296034,0.321806,0.324699,0.285588,0
7,7,dsgdb9nsd_000002,2,0.310641,0.3600,0.150647,-0.716873,0.642828,0.362992,0.363300,0.296035,0.321807,0.324699,0.285589,0
8,8,dsgdb9nsd_000002,3,0.310643,0.3600,0.150647,-0.716941,0.642891,0.362994,0.363302,0.296037,0.321809,0.324701,0.285591,0
9,9,dsgdb9nsd_000003,0,-0.636727,-0.8600,-0.576388,1.742329,-1.420778,-0.984997,-0.804795,-0.859773,-0.928456,-0.688535,-0.841479,0
10,10,dsgdb9nsd_000003,1,0.318363,0.4300,0.288194,-0.871165,0.710389,0.492498,0.402398,0.429886,0.464228,0.344268,0.420740,0
11,11,dsgdb9nsd_000003,2,0.318363,0.4300,0.288194,-0.871165,0.710389,0.492498,0.402398,0.429886,0.464228,0.344268,0.420740,0
12,12,dsgdb9nsd_000005,0,0.141888,0.3801,0.066250,-0.450498,0.366718,0.884638,-0.130032,0.123579,0.727763,-0.220970,0.091352,0
13,13,dsgdb9nsd_000005,1,-0.283738,-0.5571,-0.443226,0.424599,-0.269240,-0.955701,-0.129120,-0.260531,-0.780675,-0.031063,-0.235617,0
14,14,dsgdb9nsd_000005,2,0.141851,0.1770,0.376976,0.025899,-0.097478,0.071062,0.259152,0.136952,0.052912,0.252033,0.144265,0
15,15,dsgdb9nsd_000007,0,-0.401703,0.0000,-0.068144,0.776693,-0.685050,0.010054,-0.562867,-0.504271,-0.045145,-0.567597,-0.550975,0
16,16,dsgdb9nsd_000007,1,-0.401703,0.0000,-0.068144,0.776709,-0.685065,0.010054,-0.562868,-0.504271,-0.045145,-0.567597,-0.550975,0
17,17,dsgdb9nsd_000007,2,0.133902,0.0000,0.022715,-0.258903,0.228355,-0.003351,0.187624,0.168092,0.015048,0.189200,0.183660,0
18,18,dsgdb9nsd_000007,3,0.133901,0.0000,0.022715,-0.258899,0.228352,-0.003351,0.187623,0.168091,0.015048,0.189199,0.183659,0
19,19,dsgdb9nsd_000007,4,0.133899,0.0000,0.022715,-0.258891,0.228344,-0.003351,0.187621,0.168088,0.015048,0.189197,0.183656,0

In [10]:
tst_ob.head()

,Unnamed: 0,molecule_name,atom_index,eem,mmff94,gasteiger,qeq,qtpie,eem2015ha,eem2015hm,eem2015hn,eem2015ba,eem2015bm,eem2015bn,error
0,0,dsgdb9nsd_000004,0,-0.140218,-0.177,-0.195499,0.162134,-0.104823,0.186739,-0.244665,-0.126079,0.188397,-0.232962,-0.126054,0
1,1,dsgdb9nsd_000004,1,-0.140218,-0.177,-0.195499,0.162134,-0.104823,0.186739,-0.244665,-0.126079,0.188397,-0.232962,-0.126054,0
2,2,dsgdb9nsd_000004,2,0.140218,0.177,0.195499,-0.162134,0.104823,-0.186739,0.244665,0.126079,-0.188397,0.232962,0.126054,0
3,3,dsgdb9nsd_000004,3,0.140218,0.177,0.195499,-0.162134,0.104823,-0.186739,0.244665,0.126079,-0.188397,0.232962,0.126054,0
4,4,dsgdb9nsd_000015,0,-0.200372,0.280,-0.018924,-0.438607,0.348798,0.462935,-0.319256,-0.257585,0.347919,-0.405719,-0.346147,0

In [12]:
trn_geom.head()

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant,num_atoms,flatness_metric,bond_angle_plane,bond_angle_axis
0,0,dsgdb9nsd_000001,1,0,1JHC,84.8076,5,0.443763,52.084336,34.460723
1,1,dsgdb9nsd_000001,1,2,2JHH,-11.2570,5,0.443763,73.351369,0.804151
2,2,dsgdb9nsd_000001,1,3,2JHH,-11.2548,5,0.443763,39.073646,44.696643
3,3,dsgdb9nsd_000001,1,4,2JHH,-11.2543,5,0.443763,20.124275,44.160491
4,4,dsgdb9nsd_000001,2,0,1JHC,84.8074,5,0.443763,50.858953,36.069061

In [18]:
angles = pd.read_csv(f'./data/angles.csv')

In [21]:
angles.head(10)

,molecule_name,atom_index_0,atom_index_1,shortest_path_atoms,shortest_path_n_bonds,cosinus,dihedral
0,dsgdb9nsd_000001,1,0,NaN,1,NaN,NaN
1,dsgdb9nsd_000001,1,2,C,2,-0.33329,NaN
2,dsgdb9nsd_000001,1,3,C,2,-0.33333,NaN
3,dsgdb9nsd_000001,1,4,C,2,-0.33335,NaN
4,dsgdb9nsd_000001,2,0,NaN,1,NaN,NaN
5,dsgdb9nsd_000001,2,3,C,2,-0.33335,NaN
6,dsgdb9nsd_000001,2,4,C,2,-0.33334,NaN
7,dsgdb9nsd_000001,3,0,NaN,1,NaN,NaN
8,dsgdb9nsd_000001,3,4,C,2,-0.33334,NaN
9,dsgdb9nsd_000001,4,0,NaN,1,NaN,NaN

In [13]:
dipole_moments.head(10)

      molecule_name       X       Y       Z
0  dsgdb9nsd_000001  0.0000  0.0000  0.0000
1  dsgdb9nsd_000002 -0.0002  0.0000  1.6256
2  dsgdb9nsd_000003  0.0000  0.0000 -1.8511
3  dsgdb9nsd_000005  0.0000  0.0000 -2.8937
4  dsgdb9nsd_000007  0.0000  0.0000  0.0000
5  dsgdb9nsd_000008  0.6506 -1.3801 -0.0002
6  dsgdb9nsd_000009  0.7156  0.0004 -0.0004
7  dsgdb9nsd_000010  3.8266  0.0000 -0.0001
8  dsgdb9nsd_000011  2.3605  1.0119  0.0004
9  dsgdb9nsd_000012 -3.6612  0.7058  0.0009

In [15]:
magnetic_shielding_tensors.head(10)

,molecule_name,atom_index,XX,YX,ZX,XY,YY,ZY,XZ,YZ,ZZ
0,dsgdb9nsd_000001,0,195.3150,0.0000,-0.0001,0.0000,195.3170,0.0007,-0.0001,0.0007,195.3170
1,dsgdb9nsd_000001,1,31.3410,-1.2317,4.0544,-1.2317,28.9546,-1.7173,4.0546,-1.7173,34.0861
2,dsgdb9nsd_000001,2,31.5814,1.2173,-4.1474,1.2173,28.9036,-1.6036,-4.1476,-1.6036,33.8967
3,dsgdb9nsd_000001,3,31.5172,4.1086,1.2723,4.1088,33.9068,1.6950,1.2724,1.6951,28.9579
4,dsgdb9nsd_000001,4,31.4029,-4.0942,-1.1793,-4.0944,34.0776,1.6259,-1.1795,1.6260,28.9013
5,dsgdb9nsd_000002,0,275.6350,0.0003,0.0133,0.0003,275.6360,-0.0003,0.0161,-0.0004,237.4970
6,dsgdb9nsd_000002,1,31.2593,5.6126,-2.1025,5.6136,37.4364,-3.5567,-2.4461,-4.1372,27.9884
7,dsgdb9nsd_000002,2,31.0341,-5.4827,-2.0299,-5.4837,37.6618,3.5987,-2.3616,4.1861,27.9885
8,dsgdb9nsd_000002,3,40.7507,-0.1300,4.1318,-0.1300,27.9413,-0.0419,4.8083,-0.0488,27.9889
9,dsgdb9nsd_000003,0,310.0960,0.0000,0.0000,0.0000,355.7730,0.0000,0.0000,0.0000,324.1550

In [16]:
mulliken_charges.head(50)

       molecule_name  atom_index  mulliken_charge
0   dsgdb9nsd_000001           0        -0.535689
1   dsgdb9nsd_000001           1         0.133921
2   dsgdb9nsd_000001           2         0.133922
3   dsgdb9nsd_000001           3         0.133923
4   dsgdb9nsd_000001           4         0.133923
5   dsgdb9nsd_000002           0        -0.707143
6   dsgdb9nsd_000002           1         0.235712
7   dsgdb9nsd_000002           2         0.235712
8   dsgdb9nsd_000002           3         0.235720
9   dsgdb9nsd_000003           0        -0.589706
10  dsgdb9nsd_000003           1         0.294853
11  dsgdb9nsd_000003           2         0.294853
12  dsgdb9nsd_000005           0        -0.049655
13  dsgdb9nsd_000005           1        -0.188473
14  dsgdb9nsd_000005           2         0.238128
15  dsgdb9nsd_000007           0        -0.345672
16  dsgdb9nsd_000007           1        -0.345672
17  dsgdb9nsd_000007           2         0.115222
18  dsgdb9nsd_000007           3         0.115225
19  dsgdb9nsd_000007           4         0.115225
20  dsgdb9nsd_000007           5         0.115225
21  dsgdb9nsd_000007           6         0.115222
22  dsgdb9nsd_000007           7         0.115225
23  dsgdb9nsd_000008           0        -0.220179
24  dsgdb9nsd_000008           1        -0.403148
25  dsgdb9nsd_000008           2         0.102778
26  dsgdb9nsd_000008           3         0.102783
27  dsgdb9nsd_000008           4         0.131574
28  dsgdb9nsd_000008           5         0.286193
29  dsgdb9nsd_000009           0        -0.493018
30  dsgdb9nsd_000009           1         0.286586
31  dsgdb9nsd_000009           2        -0.443025
32  dsgdb9nsd_000009           3         0.151087
33  dsgdb9nsd_000009           4         0.151092
34  dsgdb9nsd_000009           5         0.151097
35  dsgdb9nsd_000009           6         0.196182
36  dsgdb9nsd_000010           0        -0.490926
37  dsgdb9nsd_000010           1         0.247402
38  dsgdb9nsd_000010           2        -0.285473
39  dsgdb9nsd_000010           3         0.176340
40  dsgdb9nsd_000010           4         0.176328
41  dsgdb9nsd_000010           5         0.176329
42  dsgdb9nsd_000011           0        -0.450295
43  dsgdb9nsd_000011           1         0.172068
44  dsgdb9nsd_000011           2        -0.225967
45  dsgdb9nsd_000011           3         0.145454
46  dsgdb9nsd_000011           4         0.143237
47  dsgdb9nsd_000011           5         0.143266
48  dsgdb9nsd_000011           6         0.072238
49  dsgdb9nsd_000012           0        -0.463064

In [ ]:
potential_energy.head(20)

In [ ]:
scal_coup_contrib.head(50)

In [17]:
structures.head(50)

       molecule_name  atom_index atom         x         y         z
0   dsgdb9nsd_000001           0    C -0.012698  1.085804  0.008001
1   dsgdb9nsd_000001           1    H  0.002150 -0.006031  0.001976
2   dsgdb9nsd_000001           2    H  1.011731  1.463751  0.000277
3   dsgdb9nsd_000001           3    H -0.540815  1.447527 -0.876644
4   dsgdb9nsd_000001           4    H -0.523814  1.437933  0.906397
5   dsgdb9nsd_000002           0    N -0.040426  1.024108  0.062564
6   dsgdb9nsd_000002           1    H  0.017257  0.012545 -0.027377
7   dsgdb9nsd_000002           2    H  0.915789  1.358745 -0.028758
8   dsgdb9nsd_000002           3    H -0.520278  1.343532 -0.775543
9   dsgdb9nsd_000003           0    O -0.034360  0.977540  0.007602
10  dsgdb9nsd_000003           1    H  0.064766  0.020572  0.001535
11  dsgdb9nsd_000003           2    H  0.871790  1.300792  0.000693
12  dsgdb9nsd_000004           0    C  0.599539  0.000000  1.000000
13  dsgdb9nsd_000004           1    C -0.599539  0.000000  1.000000
14  dsgdb9nsd_000004           2    H -1.661639  0.000000  1.000000
15  dsgdb9nsd_000004           3    H  1.661639  0.000000  1.000000
16  dsgdb9nsd_000005           0    C -0.013324  1.132466  0.008276
17  dsgdb9nsd_000005           1    N  0.002311 -0.019159  0.001929
18  dsgdb9nsd_000005           2    H -0.027803  2.198949  0.014154
19  dsgdb9nsd_000007           0    C -0.018704  1.525582  0.010433
20  dsgdb9nsd_000007           1    C  0.002104 -0.003882  0.001999
21  dsgdb9nsd_000007           2    H  0.994873  1.939743  0.002941
22  dsgdb9nsd_000007           3    H -0.542076  1.923611 -0.865117
23  dsgdb9nsd_000007           4    H -0.525241  1.914173  0.900024
24  dsgdb9nsd_000007           5    H  0.525487 -0.401908  0.877544
25  dsgdb9nsd_000007           6    H -1.011477 -0.418034  0.009508
26  dsgdb9nsd_000007           7    H  0.508626 -0.392470 -0.887601
27  dsgdb9nsd_000008           0    C -0.008288  1.390470 -0.005601
28  dsgdb9nsd_000008           1    O -0.007970 -0.025045  0.020306
29  dsgdb9nsd_000008           2    H  1.006583  1.815564  0.003483
30  dsgdb9nsd_000008           3    H -0.546575  1.799170 -0.873901
31  dsgdb9nsd_000008           4    H -0.522889  1.725552  0.899073
32  dsgdb9nsd_000008           5    H  0.441420 -0.333544 -0.771521
33  dsgdb9nsd_000009           0    C -0.017821  1.464358  0.010094
34  dsgdb9nsd_000009           1    C  0.002088  0.009508  0.002012
35  dsgdb9nsd_000009           2    C  0.018341 -1.191805 -0.004505
36  dsgdb9nsd_000009           3    H  0.997822  1.874253  0.002606
37  dsgdb9nsd_000009           4    H -0.542204  1.858012 -0.867212
38  dsgdb9nsd_000009           5    H -0.525333  1.848344  0.901481
39  dsgdb9nsd_000009           6    H  0.032317 -2.253148 -0.010260
40  dsgdb9nsd_000010           0    C -0.017886  1.467128  0.010113
41  dsgdb9nsd_000010           1    C  0.001738  0.010353  0.002076
42  dsgdb9nsd_000010           2    N  0.017652 -1.144529 -0.004204
43  dsgdb9nsd_000010           3    H  1.002029  1.860899  0.002454
44  dsgdb9nsd_000010           4    H -0.543988  1.844799 -0.870755
45  dsgdb9nsd_000010           5    H -0.527078  1.835182  0.904863
46  dsgdb9nsd_000011           0    C -0.002945  1.509914  0.008673
47  dsgdb9nsd_000011           1    C  0.026083  0.003276 -0.037459
48  dsgdb9nsd_000011           2    O  0.942288 -0.655070 -0.456826
49  dsgdb9nsd_000011           3    H  0.922788  1.926342 -0.391466